name: weather_app_test
description: A new Flutter weather app project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.4.0
  geolocator: ^10.1.0
  intl: ^0.18.1
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/home.png
    - assets/images/house.png
    - assets/images/box.png
    - assets/images/tab.png
